name: rnp
base: core18
adopt-info: rnp
summary: High performance C++ OpenPGP tools, fully compliant to RFC 4880 # 79 char long summary
description: |
  RNP is a set of OpenPGP (RFC4880) tools that works on Linux, *BSD and macOS as a replacement of GnuPG.
  It is maintained by Ribose after being forked from NetPGP, itself originally written for NetBSD.

grade: stable
confinement: strict

parts:
  rnp:
    after: ["botan2"]
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag -l --sort=-v:refname | head -1)"
      VERSION=${last_committed_tag}
      git fetch
      git checkout "${VERSION}"
      echo "Setting version to $VERSION"
      snapcraftctl set-version "${VERSION}"
    source-type: git
    source: https://github.com/rnpgp/rnp.git
    build-packages:
      - g++
      - make
      - cmake
      - libbz2-dev
      - libz-dev
      - libjson-c-dev
    stage-packages:
      - bzip2
      - zlib1g
      - libjson-c3
    prime:
      - bin/rnp
      - bin/rnpkeys
  botan2:
    plugin: make
    override-build: ./configure.py --prefix=/usr && snapcraftctl build
    source: https://botan.randombit.net/releases/Botan-2.12.1.tar.xz
    build-packages:
      - g++
      - make
      - python-minimal
    stage-packages:
      - bzip2
      - zlib1g
    prime:
      - usr/lib/libbotan*.so*
apps:
  rnp:
    command: bin/rnp
  rnpkeys:
    command: bin/rnpkeys
