name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
    - name: Build snap
      env: 
        SNAPCRAFT_BUILD_ENVIRONMENT: host
      run: snapcraft snap --output=rnp_latest.snap
    - name: Push snap
      run: |
        echo "${{ secrets.SNAPCRAFT_RELEASE_LOGIN }}" > snap-exported-login
        snapcraft login --with snap-exported-login
        snapcraft push --release=edge rnp_latest.snap
