name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.SNAP_DEPLOY_SSH_KEY }}
    - name: Build snap
      env: 
        SNAPCRAFT_BUILD_ENVIRONMENT: managed-host
        PC_BOTAN2_INCLUDEDIR: ${{ github.workspace }}/stage/include
        PC_BOTAN2_LIBDIR: ${{ github.workspace }}/stage/lib
      run: snapcraft snap --output=rnp_latest.snap
    - name: Push snap
      run: snapcraft push --release=edge rnp_latest.snap
